#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apt'

cookbook 'rvm',
  :git => 'git://github.com/fnichol/chef-rvm.git'

cookbook 'debootstrap',
  :git => 'git://github.com/vpslab/debootstrap-cookbook.git'

cookbook 'warden',
  :git => 'git://github.com/thoward/warden-cookbook.git'
